 name: gitartwork from a contribution graph
 on: 
   push:
   schedule:
     - cron: '* */24 * * *'
   workflow_dispatch:
 jobs:
   build:
     name: Make gitartwork SVG
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
         with:
          repository: shentuzhigang/shentuzhigang.github.io
          ref: gh-pages
          token: ${{ secrets.GH_PAGES_TOKEN }}
       - uses: jasineri/gitartwork@v1
         with:
            # Use this username's contribution graph  
            user_name: shentuzhigang
            # Text on contribution graph 
            text: Starzkg
       - uses: stefanzweifel/git-auto-commit-action@v4
         with:
          commit_message: gitartwork SVG 
